#!/usr/bin/env python3
#
# database for wyckoff position and generator
#  this data was generated by Akira Yanase
#  implemented for python library by Hiroki Funashima
#
#
# Prof. Yanase have copyright for this database.
#


class LibTspaceDataBase(object):
    def wyckoff_database(self):
        wyckoff = '''
              1  1
             1a x y z
              2  9
             1a 0 0 0
             1b 0 0 h
             1c 0 h 0
             1d h 0 0
             1e h h 0
             1f h 0 h
             1g 0 h h
             1h h h h
             2i x y z
              3  5
             1a 0 y 0
             1b 0 y h
             1c h y 0
             1d h y h
             2e x y z
              3  5
             1a 0 0 z
             1b h 0 z
             1c 0 h z
             1d h h z
             2e x y z
              4  1
             2a x y z
              4  1
             2a x y z
              5  3
             2a 0 y 0
             2b 0 y h
             4c x y z
              5  3
             2a 0 y 0
             2b h y 0
             4c x y z
              5  3
             2a 0 0 z
             2b 0 h z
             4c x y z
              6  3
             1a x 0 z
             1b x h z
             2c x y z
              6  3
             1a x y 0
             1b x y h
             2c x y z
              7  1
             2a x y z
              7  1
             2a x y z
              7  1
             2a x y z
              7  1
             2a x y z
              7  1
             2a x y z
              7  1
             2a x y z
              8  2
             2a x 0 z
             4b x y z
              8  2
             2a x 0 z
             4b x y z
              8  2
             2a x y 0
             4b x y z
              9  1
             4a x y z
              9  1
             4a x y z
              9  1
             4a x y z
             10 15
             1a 0 0 0
             1b 0 h 0
             1c 0 0 h
             1d h 0 0
             1e h h 0
             1f 0 h h
             1g h 0 h
             1h h h h
             2i 0 y 0
             2j h y 0
             2k 0 y h
             2l h y h
             2m x 0 z
             2n x h z
             4o x y z
             10 15
             1a 0 0 0
             1b 0 0 h
             1c h 0 0
             1d 0 h 0
             1e 0 h h
             1f h 0 h
             1g h h 0
             1h h h h
             2i 0 0 z
             2j 0 h z
             2k h 0 z
             2l h h z
             2m x y 0
             2n x y h
             4o x y z
             11  6
             2a 0 0 0
             2b h 0 0
             2c 0 0 h
             2d h 0 h
             2e x q z
             4f x y z
             11  6
             2a 0 0 0
             2b 0 h 0
             2c h 0 0
             2d h h 0
             2e x y q
             4f x y z
             12 10
             2a 0 0 0
             2b 0 h 0
             2c 0 0 h
             2d 0 h h
             4e q q 0
             4f q q h
             4g 0 y 0
             4h 0 y h
             4i x 0 z
             8j x y z
             12 10
             2a 0 0 0
             2b 0 h 0
             2c h 0 0
             2d h h 0
             4e t q t
             4f q q t
             4g 0 y 0
             4h h y 0
             4i x 0 z
             8j x y z
             12 10
             2a 0 0 0
             2b 0 0 h
             2c 0 h 0
             2d 0 h h
             4e t t q
             4f t q q
             4g 0 0 z
             4h 0 h z
             4i x y 0
             8j x y z
             13  7
             2a 0 0 0
             2b h h 0
             2c 0 h 0
             2d h 0 0
             2e 0 y q
             2f h y q
             4g x y z
             13  7
             2a 0 0 0
             2b 0 h h
             2c 0 h 0
             2d 0 0 h
             2e t y t
             2f t y q
             4g x y z
             13  7
             2a 0 0 0
             2b h h h
             2c 0 h 0
             2d h 0 h
             2e q y 0
             2f t y h
             4g x y z
             13  7
             2a 0 0 0
             2b 0 h h
             2c 0 0 h
             2d 0 h 0
             2e q 0 z
             2f q h z
             4g x y z
             13  7
             2a 0 0 0
             2b h 0 h
             2c 0 0 h
             2d h 0 0
             2e t t z
             2f q t z
             4g x y z
             13  7
             2a 0 0 0
             2b h h h
             2c 0 0 h
             2d h h 0
             2e 0 q z
             2f h t z
             4g x y z
             14  5
             2a 0 0 0
             2b h 0 0
             2c 0 0 h
             2d h 0 h
             4e x y z
             14  5
             2a 0 0 0
             2b 0 0 h
             2c h 0 h
             2d h 0 0
             4e x y z
             14  5
             2a 0 0 0
             2b h 0 h
             2c h 0 0
             2d 0 0 h
             4e x y z
             14  5
             2a 0 0 0
             2b 0 h 0
             2c h 0 0
             2d h h 0
             4e x y z
             14  5
             2a 0 0 0
             2b h 0 0
             2c h h 0
             2d 0 h 0
             4e x y z
             14  5
             2a 0 0 0
             2b h h 0
             2c 0 h 0
             2d h 0 0
             4e x y z
             15  6
             4a 0 0 0
             4b 0 h 0
             4c q q 0
             4d q q h
             4e 0 y q
             8f x y z
             15  6
             4a 0 0 0
             4b 0 h 0
             4c t q t
             4d q q t
             4e q y 0
             8f x y z
             15  6
             4a 0 0 0
             4b 0 0 h
             4c t t q
             4d t q q
             4e 0 q z
             8f x y z
             16 21
             1a 0 0 0
             1b h 0 0
             1c 0 h 0
             1d 0 0 h
             1e h h 0
             1f h 0 h
             1g 0 h h
             1h h h h
             2i x 0 0
             2j x 0 h
             2k x h 0
             2l x h h
             2m 0 y 0
             2n 0 y h
             2o h y 0
             2p h y h
             2q 0 0 z
             2r h 0 z
             2s 0 h z
             2t h h z
             4u x y z
             17  5
             2a x 0 0
             2b x h 0
             2c 0 y q
             2d h y q
             4e x y z
             18  3
             2a 0 0 z
             2b 0 h z
             4c x y z
             19  1
             4a x y z
             20  3
             4a x 0 0
             4b 0 y q
             8c x y z
             21 12
             2a 0 0 0
             2b 0 h 0
             2c h 0 h
             2d 0 0 h
             4e x 0 0
             4f x 0 h
             4g 0 y 0
             4h 0 y h
             4i 0 0 z
             4j 0 h z
             4k q q z
             8l x y z
             22 11
             4a 0 0 0
             4b 0 0 h
             4c q q q
             4d q q t
             8e x 0 0
             8f 0 y 0
             8g 0 0 z
             8h q q z
             8i q y q
             8j x q q
            16k x y z
             23 11
             2a 0 0 0
             2b h 0 0
             2c 0 0 h
             2d 0 h 0
             4e x 0 0
             4f x 0 h
             4g 0 y 0
             4h h y 0
             4i 0 0 z
             4j 0 h z
             8k x y z
             24  4
             4a x 0 q
             4b q y 0
             4c 0 q z
             8d x y z
             25  9
             1a 0 0 z
             1b 0 h z
             1c h 0 z
             1d h h z
             2e x 0 z
             2f x h z
             2g 0 y z
             2h h y z
             4i x y z
             26  3
             2a 0 y z
             2b h y z
             4c x y z
             27  5
             2a 0 0 z
             2b 0 h z
             2c h 0 z
             2d h h z
             4e x y z
             28  4
             2a 0 0 z
             2b 0 h z
             2c q y z
             4d x y z
             29  1
             4a x y z
             30  3
             2a 0 0 z
             2b h 0 z
             4c x y z
             31  2
             2a 0 y z
             4b x y z
             32  3
             2a 0 0 z
             2b 0 h z
             4c x y z
             33  1
             4a x y z
             34  3
             2a 0 0 z
             2b 0 h z
             4c x y z
             35  6
             2a 0 0 z
             2b 0 h z
             4c q q z
             4d x 0 z
             4e 0 y z
             8f x y z
             36  2
             4a 0 y z
             8b x y z
             37  4
             4a 0 0 z
             4b 0 h z
             4c q q z
             8d x y z
             38  6
             2a 0 y 0
             2b 0 y h
             4c 0 y z
             4d x y 0
             4e x y h
             8f x y z
             39  4
             4a 0 y 0
             4b 0 y h
             4c q y z
             8d x y z
             40  3
             4a 0 y 0
             4b x y q
             8c x y z
             41  2
             4a 0 y 0
             8b x y z
             42  5
             4a 0 0 z
             8b q q z
             8c 0 y z
             8d x 0 z
            16e x y z
             43  2
             8a 0 0 z
            16b x y z
             44  5
             2a 0 0 z
             2b 0 h z
             4c x 0 z
             4d 0 y z
             8e x y z
             45  3
             4a 0 0 z
             4b 0 h z
             8c x y z
             46  3
             4a 0 0 z
             4b q y z
             8c x y z
             47 27
             1a 0 0 0
             1b h 0 0
             1c 0 0 h
             1d h 0 h
             1e 0 h 0
             1f h h 0
             1g 0 h h
             1h h h h
             2i x 0 0
             2j x 0 h
             2k x h 0
             2l x h h
             2m 0 y 0
             2n 0 y h
             2o h y 0
             2p h y h
             2q 0 0 z
             2r 0 h z
             2s h 0 z
             2t h h z
             4u 0 y z
             4v h y z
             4w x 0 z
             4x x h z
             4y x y 0
             4z x y h
             80 x y z
             48 13
             2a 0 0 0
             2b h 0 0
             2c 0 0 h
             2d 0 h 0
             4e q q q
             4f t t t
             4g x 0 0
             4h x 0 h
             4i 0 y 0
             4j h y 0
             4k 0 0 z
             4l 0 h z
             8m x y z
             48 13
             2a q q q
             2b t q q
             2c q q t
             2d q t q
             4e h h h
             4f 0 0 0
             4g x q q
             4h x q t
             4i q y q
             4j t y q
             4k q q z
             4l q t z
             8m x y z
             49 18
             2a 0 0 0
             2b h h 0
             2c 0 h 0
             2d h 0 0
             2e 0 0 h
             2f h 0 q
             2g 0 h q
             2h h h q
             4i x 0 q
             4j x h q
             4k 0 y q
             4l h y q
             4m 0 0 z
             4n h h z
             4o 0 h z
             4p h 0 z
             4q x y 0
             8r x y z
             50 13
             2a 0 0 0
             2b h 0 0
             2c h 0 h
             2d 0 0 h
             4e q q 0
             4f q q h
             4g x 0 0
             4h x 0 h
             4i 0 y 0
             4j 0 y h
             4k 0 0 z
             4l 0 h z
             8m x y z
             50 13
             2a q q 0
             2b t q 0
             2c t q h
             2d q q h
             4e 0 0 0
             4f 0 0 h
             4g x q 0
             4h x q h
             4i q y 0
             4j q y h
             4k q q z
             4l q t z
             8m x y z
             51 12
             2a 0 0 0
             2b 0 h 0
             2c 0 0 h
             2d 0 h h
             2e q 0 z
             2f q h z
             4g 0 y 0
             4h 0 y h
             4i x 0 z
             4j x h z
             4k q y z
             8l x y z
             52  5
             4a 0 0 0
             4b 0 0 h
             4c q 0 z
             4d x q q
             8e x y z
             53  9
             2a 0 0 0
             2b h 0 0
             2c h h 0
             2d 0 h 0
             4e x 0 0
             4f x h 0
             4g q y q
             4h 0 y z
             8i x y z
             54  6
             4a 0 0 0
             4b 0 h 0
             4c 0 y q
             4d q 0 z
             4e q h z
             8f x y z
             55  9
             2a 0 0 0
             2b 0 0 h
             2c 0 h 0
             2d 0 h h
             4e 0 0 z
             4f 0 h z
             4g x y 0
             4h x y h
             8i x y z
             56  5
             4a 0 0 0
             4b 0 0 h
             4c q q z
             4d q t z
             8e x y z
             57  5
             4a 0 0 0
             4b h 0 0
             4c x q 0
             4d x y q
             8e x y z
             58  8
             2a 0 0 0
             2b 0 0 h
             2c 0 h 0
             2d 0 h h
             4e 0 0 z
             4f 0 h z
             4g x y 0
             8h x y z
             59  7
             2a 0 0 z
             2b 0 h z
             4c q q 0
             4d q q h
             4e 0 y z
             4f x 0 z
             8g x y z
             59  7
             2a q q z
             2b q t z
             4c 0 0 0
             4d 0 0 h
             4e q y z
             4f x q z
             8g x y z
             60  4
             4a 0 0 0
             4b 0 h 0
             4c 0 y q
             8d x y z
             61  3
             4a 0 0 0
             4b 0 0 h
             8c x y z
             62  4
             4a 0 0 0
             4b 0 0 h
             4c x q z
             8d x y z
             63  8
             4a 0 0 0
             4b 0 h 0
             4c 0 y q
             8d q q 0
             8e x 0 0
             8f 0 y z
             8g x y q
            16h x y z
             64  7
             4a 0 0 0
             4b h 0 0
             8c q q 0
             8d x 0 0
             8e q y q
             8f 0 y z
            16g x y z
             65 18
             2a 0 0 0
             2b h 0 0
             2c h 0 h
             2d 0 0 h
             4e q q 0
             4f q q h
             4g x 0 0
             4h x 0 h
             4i 0 y 0
             4j 0 y h
             4k 0 0 z
             4l 0 h z
             8m q q z
             8n 0 y z
             8o x 0 z
             8p x y 0
             8q x y h
            16r x y z
             66 13
             4a 0 0 q
             4b 0 h q
             4c 0 0 0
             4d 0 h 0
             4e q q 0
             4f q t 0
             8g x 0 q
             8h 0 y q
             8i 0 0 z
             8j 0 h z
             8k q q z
             8l x y 0
            16m x y z
             67 15
             4a q 0 0
             4b q 0 h
             4c 0 0 0
             4d 0 0 h
             4e q q 0
             4f q q h
             4g 0 q z
             8h x 0 0
             8i x 0 h
             8j q y 0
             8k q y h
             8l q 0 z
             8m 0 y z
             8n x q z
            16o x y z
             68  9
             4a 0 0 0
             4b 0 0 h
             8c q 0 q
             8d 0 q q
             8e x 0 0
             8f 0 y 0
             8g 0 0 z
             8h q q z
            16i x y z
             68  9
             4a 0 q q
             4b 0 q t
             8c q t 0
             8d 0 0 0
             8e x q q
             8f 0 y q
             8g 0 q z
             8h q 0 z
            16i x y z
             69 16
             4a 0 0 0
             4b 0 0 h
             8c 0 q q
             8d q 0 q
             8e q q 0
             8f q q q
             8g x 0 0
             8h 0 y 0
             8i 0 0 z
            16j q q z
            16k q y q
            16l x q q
            16m 0 y z
            16n x 0 z
            16o x y 0
            32p x y z
             70  8
             8a 0 0 0
             8b 0 0 h
            16c 8 8 8
            16d f f f
            16e x 0 0
            16f 0 y 0
            16g 0 0 z
            32h x y z
             70  8
             8a 8 8 8
             8b 8 8 f
            16c 0 0 0
            16d h h h
            16e x 8 8
            16f 8 y 8
            16g 8 8 z
            32h x y z
             71 15
             2a 0 0 0
             2b 0 h h
             2c h h 0
             2d h 0 h
             4e x 0 0
             4f x h 0
             4g 0 y 0
             4h 0 y h
             4i 0 0 z
             4j h 0 z
             8k q q q
             8l 0 y z
             8m x 0 z
             8n x y 0
            16o x y z
             72 11
             4a 0 0 q
             4b h 0 q
             4c 0 0 0
             4d h 0 0
             8e q q q
             8f x 0 q
             8g 0 y q
             8h 0 0 z
             8i 0 h z
             8j x y 0
            16k x y z
             73  6
             8a 0 0 0
             8b q q q
             8c x 0 q
             8d q y 0
             8e 0 q z
            16f x y z
             74 10
             4a 0 0 0
             4b 0 0 h
             4c q q q
             4d q q t
             4e 0 q z
             8f x 0 0
             8g q y q
             8h 0 y z
             8i x q z
            16j x y z
             75  4
             1a 0 0 z
             1b h h z
             2c 0 h z
             4d x y z
             76 1
             4a x y z
             77  4
             2a 0 0 z
             2b h h z
             2c 0 h z
             4d x y z
             78  1
             4a x y z
             79  3
             2a 0 0 z
             4b 0 h z
             8c x y z
             80  2
             4a 0 0 z
             8b x y z
             81  8
             1a 0 0 0
             1b 0 0 h
             1c h h 0
             1d h h h
             2e 0 0 z
             2f h h z
             2g 0 h z
             4h x y z
             82  7
             2a 0 0 0
             2b 0 0 h
             2c 0 h q
             2d 0 h t
             4e 0 0 z
             4f 0 h z
             8g x y z
             83 12
             1a 0 0 0
             1b 0 0 h
             1c h h 0
             1d h h h
             2e 0 h 0
             2f 0 h h
             2g 0 0 z
             2h h h z
             4i 0 h z
             4j x y 0
             4k x y h
             8l x y z
             84 11
             2a 0 0 0
             2b h h 0
             2c 0 h 0
             2d 0 h h
             2e 0 0 q
             2f h h q
             4g 0 0 z
             4h h h z
             4i 0 h z
             4j x y 0
             8k x y z
             85  7
             2a 0 0 0
             2b 0 0 h
             2c 0 h z
             4d q q 0
             4e q q h
             4f 0 0 z
             8g x y z
             85  7
             2a q t 0
             2b q t h
             2c q q z
             4d 0 0 0
             4e 0 0 h
             4f q t z
             8g x y z
             86  7
             2a 0 0 0
             2b 0 0 h
             4c q q q
             4d q q t
             4e 0 h z
             4f 0 0 z
             8g x y z
             86  7
             2a q q q
             2b q q t
             4c 0 0 0
             4d 0 0 h
             4e t q z
             4f q q z
             8g x y z
             87  9
             2a 0 0 0
             2b 0 0 h
             4c 0 h 0
             4d 0 h q
             4e 0 0 z
             8f q q q
             8g 0 h z
             8h x y 0
            16i x y z
             88  6
             4a 0 0 0
             4b 0 0 h
             8c 0 q 8
             8d 0 q f
             8e 0 0 z
            16f x y z
             88  6
             4a 0 q 8
             4b 0 q f
             8c 0 0 0
             8d 0 0 h
             8e 0 q z
            16f x y z
             89 16
             1a 0 0 0
             1b 0 0 h
             1c h h 0
             1d h h h
             2e h 0 0
             2f h 0 h
             2g 0 0 z
             2h h h z
             4i 0 h z
             4j x x 0
             4k x x h
             4l x 0 0
             4m x h h
             4n x 0 h
             4o x h 0
             8p x y z
             90  7
             2a 0 0 0
             2b 0 0 h
             2c 0 h z
             4d 0 0 z
             4e x x 0
             4f x x h
             8g x y z
             91  4
             4a 0 y 0
             4b h y 0
             4c x x 3
             8d x y z
             92  2
             4a x x 0
             8b x y z
             93 16
             2a 0 0 0
             2b h h 0
             2c 0 h 0
             2d 0 h h
             2e 0 0 q
             2f h h q
             4g 0 0 z
             4h h h z
             4i 0 h z
             4j x 0 0
             4k x h h
             4l x 0 h
             4m x h 0
             4n x x q
             4o x x t
             8p x y z
             94  7
             2a 0 0 0
             2b 0 0 h
             4c 0 0 z
             4d 0 h z
             4e x x 0
             4f x x h
             8g x y z
             95  4
             4a 0 y 0
             4b h y 0
             4c x x f
             8d x y z
             96  2
             4a x x 0
             8b x y z
             97 11
             2a 0 0 0
             2b 0 0 h
             4c 0 h 0
             4d 0 h q
             4e 0 0 z
             8f 0 h z
             8g x x 0
             8h x 0 0
             8i x 0 h
             8j x s q
            16k x y z
             98  7
             4a 0 0 0
             4b 0 0 h
             8c 0 0 z
             8d x x 0
             8e - x 0
             8f x q 8
            16g x y z
             99  7
             1a 0 0 z
             1b h h z
             2c h 0 z
             4d x x z
             4e x 0 z
             4f x h z
             8g x y z
            100  4
             2a 0 0 z
             2b h 0 z
             4c x s z
             8d x y z
            101  5
             2a 0 0 z
             2b h h z
             4c 0 h z
             4d x x z
             8e x y z
            102  4
             2a 0 0 z
             4b 0 h z
             4c x x z
             8d x y z
            103  4
             2a 0 0 z
             2b h h z
             4c 0 h z
             8d x y z
            104  3
             2a 0 0 z
             4b 0 h z
             8c x y z
            105  6
             2a 0 0 z
             2b h h z
             2c 0 h z
             4d x 0 z
             4e x h z
             8f x y z
            106  3
             4a 0 0 z
             4b 0 h z
             8c x y z
            107  5
             2a 0 0 z
             4b 0 h z
             8c x x z
             8d x 0 z
            16e x y z
            108  4
             4a 0 0 z
             4b h 0 z
             8c x s z
            16d x y z
            109  3
             4a 0 0 z
             8b 0 y z
            16c x y z
            110  2
             8a 0 0 z
            16b x y z
            111 15
             1a 0 0 0
             1b h h h
             1c 0 0 h
             1d h h 0
             2e h 0 0
             2f h 0 h
             2g 0 0 z
             2h h h z
             4i x 0 0
             4j x h h
             4k x 0 h
             4l x h 0
             4m 0 h z
             4n x x z
             8o x y z
            112 14
             2a 0 0 q
             2b h 0 q
             2c h h q
             2d 0 h q
             2e 0 0 0
             2f h h 0
             4g x 0 q
             4h h y q
             4i x h q
             4j 0 y q
             4k 0 0 z
             4l h h z
             4m 0 h z
             8n x y z
            113  6
             2a 0 0 0
             2b 0 0 h
             2c 0 h z
             4d 0 0 z
             4e x s z
             8f x y z
            114  5
             2a 0 0 0
             2b 0 0 h
             4c 0 0 z
             4d 0 h z
             8e x y z
            115 12
             1a 0 0 0
             1b h h 0
             1c h h h
             1d 0 0 h
             2e 0 0 z
             2f h h z
             2g 0 h z
             4h x x 0
             4i x x h
             4j x 0 z
             4k x h z
             8l x y z
            116 10
             2a 0 0 q
             2b h h q
             2c 0 0 0
             2d h h 0
             4e x x q
             4f x x t
             4g 0 0 z
             4h h h z
             4i 0 h z
             8j x y z
            117  9
             2a 0 0 0
             2b 0 0 h
             2c 0 h 0
             2d 0 h h
             4e 0 0 z
             4f 0 h z
             4g x s 0
             4h x s h
             8i x y z
            118  9
             2a 0 0 0
             2b 0 0 h
             2c 0 h q
             2d 0 h t
             4e 0 0 z
             4f x u q
             4g x s q
             4h 0 h z
             8i x y z
            119 10
             2a 0 0 0
             2b 0 0 h
             2c 0 h q
             2d 0 h t
             4e 0 0 z
             4f 0 h z
             8g x x 0
             8h x s q
             8i x 0 z
            16j x y z
            120  9
             4a 0 0 q
             4b 0 0 0
             4c 0 h q
             4d 0 h 0
             8e x x q
             8f 0 0 z
             8g 0 h z
             8h x s 0
            16i x y z
            121 10
             2a 0 0 0
             2b 0 0 h
             4c 0 h 0
             4d 0 h q
             4e 0 0 z
             8f x 0 0
             8g x 0 h
             8h 0 h z
             8i x x z
            16j x y z
            122  5
             4a 0 0 0
             4b 0 0 h
             8c 0 0 z
             8d x q 8
            16e x y z
            123 21
             1a 0 0 0
             1b 0 0 h
             1c h h 0
             1d h h h
             2e 0 h h
             2f 0 h 0
             2g 0 0 z
             2h h h z
             4i 0 h z
             4j x x 0
             4k x x h
             4l x 0 0
             4m x 0 h
             4n x h 0
             4o x h h
             8p x y 0
             8q x y h
             8r x x z
             8s x 0 z
             8t x h z
            16u x y z
            124 14
             2a 0 0 q
             2b 0 0 0
             2c h h q
             2d h h 0
             4e 0 h 0
             4f 0 h q
             4g 0 0 z
             4h h h z
             8i 0 h z
             8j x x q
             8k x 0 q
             8l x h q
             8m x y 0
            16n x y z
            125 14
             2a 0 0 0
             2b 0 0 h
             2c 0 h 0
             2d 0 h h
             4e q q 0
             4f q q h
             4g 0 0 z
             4h 0 h z
             8i x x 0
             8j x x h
             8k x 0 0
             8l x 0 h
             8m x s z
            16n x y z
            125 14
             2a q q 0
             2b q q h
             2c t q 0
             2d t q h
             4e 0 0 0
             4f 0 0 h
             4g q q z
             4h t q z
             8i x x 0
             8j x x h
             8k x q 0
             8l x q h
             8m x - z
            16n x y z
            126 11
             2a 0 0 0
             2b 0 0 h
             4c h 0 0
             4d h 0 q
             4e 0 0 z
             8f q q q
             8g h 0 z
             8h x x 0
             8i x 0 0
             8j x 0 h
            16k x y z
            126 11
             2a q q q
             2b q q t
             4c q t t
             4d q t 0
             4e q q z
             8f 0 0 0
             8g q t z
             8h x x q
             8i x q q
             8j x t q
            16k x y z
            127 12
             2a 0 0 0
             2b 0 0 h
             2c 0 h h
             2d 0 h 0
             4e 0 0 z
             4f 0 h z
             4g x s 0
             4h x s h
             8i x y 0
             8j x y h
             8k x s z
            16l x y z
            128  9
             2a 0 0 0
             2b 0 0 h
             4c 0 h 0
             4d 0 h q
             4e 0 0 z
             8f 0 h z
             8g x s q
             8h x y 0
            16i x y z
            129 11
             2a 0 0 0
             2b 0 0 h
             2c 0 h z
             4d q q 0
             4e q q h
             4f 0 0 z
             8g x x 0
             8h x x h
             8i 0 y z
             8j x s z
            16k x y z
            129 11
             2a t q 0
             2b t q h
             2c q q z
             4d 0 0 0
             4e 0 0 h
             4f t q z
             8g x - 0
             8h x - h
             8i q y z
             8j x x z
            16k x y z
            130  7
             4a 0 0 q
             4b 0 0 0
             4c 0 h z
             8d q q 0
             8e 0 0 z
             8f x x q
            16e x y z
            130  7
             4a t q q
             4b t q 0
             4c q q z
             8d 0 0 0
             8e t q z
             8f x - q
            16e x y z
            131 18
             2a 0 0 0
             2b h h 0
             2c 0 h 0
             2d 0 h h
             2e 0 0 q
             2f h h q
             4g 0 0 z
             4h h h z
             4i 0 h z
             4j x 0 0
             4k x h h
             4l x 0 h
             4m x h 0
             8n x x q
             8o 0 y z
             8p h y z
             8q x y 0
            16r x y z
            132 16
             2a 0 0 0
             2b 0 0 q
             2c h h 0
             2d h h q
             4e 0 h q
             4f 0 h 0
             4g 0 0 z
             4h h h z
             4i x x 0
             4j x x h
             8k 0 h z
             8l x 0 q
             8m x h q
             8n x y 0
             8o x x z
            16p x y z
            133 11
             4a 0 h q
             4b 0 0 q
             4c 0 h 0
             4d 0 0 0
             8e q q q
             8f 0 h z
             8g 0 0 z
             8h x 0 q
             8i x 0 t
             8j x s 0
            16k x y z
            133 11
             4a q q 0
             4b t q 0
             4c q q q
             4d t q t
             8e 0 0 0
             8f q q z
             8g t q z
             8h x q 0
             8i x q h
             8j x x q
            16k x y z
            134 14
             2a 0 0 0
             2b 0 0 h
             4c 0 h 0
             4d 0 h q
             4e q q q
             4f t t t
             4g 0 0 z
             8h 0 h z
             8i x 0 0
             8j x 0 h
             8k x s q
             8l x s t
             8m x x z
            16n x y z
            134 14
             2a q t q
             2b t q q
             4c q q q
             4d q q 0
             4e 0 0 h
             4f 0 0 0
             4g t q z
             8h q q z
             8i x q t
             8j x q q
             8k x x 0
             8l x x h
             8m x - z
            16n x y z
            135  9
             4a 0 0 0
             4b 0 0 q
             4c 0 h 0
             4d 0 h q
             8e 0 0 z
             8f 0 h z
             8g x s q
             8h x y 0
            16i x y z
            136 11
             2a 0 0 0
             2b 0 0 h
             4c 0 h 0
             4d 0 h q
             4e 0 0 z
             4f x x 0
             4g x - 0
             8h 0 h z
             8i x y 0
             8j x x z
            16k x y z
            137  8
             2a 0 0 0
             2b 0 0 h
             4c 0 0 z
             4d 0 h z
             8e q q q
             8f x x 0
             8g 0 y z
            16h x y z
            137  8
             2a t q t
             2b t q q
             4c t q z
             4d q q z
             8e 0 0 0
             8f x - q
             8g q y z
            16h x y z
            138 10
             4a 0 0 q
             4b 0 0 0
             4c q q q
             4d q q t
             4e 0 h z
             8f 0 0 z
             8g x x q
             8h x x t
             8i x s z
            16j x y z
            138 10
             4a t q 0
             4b t q t
             4c 0 0 h
             4d 0 0 0
             4e q q z
             8f t q z
             8g x - h
             8h x - 0
             8i x x z
            16j x y z
            139 15
             2a 0 0 0
             2b 0 0 h
             4c 0 h 0
             4d 0 h q
             4e 0 0 z
             8f q q q
             8g 0 h z
             8h x x 0
             8i x 0 0
             8j x h 0
            16k x s q
            16l x y 0
            16m x x z
            16n 0 y z
            32o x y z
            140 13
             4a 0 0 q
             4b 0 h q
             4c 0 0 0
             4d 0 h 0
             8e q q q
             8f 0 0 z
             8g 0 h z
             8h x s 0
            16i x x q
            16j x 0 q
            16k x y 0
            16l x s z
            32m x y z
            141  9
             4a 0 0 0
             4b 0 0 h
             8c 0 q 8
             8d 0 q f
             8e 0 0 z
            16f x q 8
            16g x x 0
            16h 0 y z
            32i x y z
            141  9
             4a 0 t 8
             4b 0 q 3
             8c 0 0 0
             8d 0 0 h
             8e 0 q z
            16f x 0 0
            16g x v 7
            16h 0 y z
            32i x y z
            142  7
             8a 0 0 0
             8b 0 0 q
            16c 0 q 8
            16d 0 0 z
            16e q y 8
            16f x x q
            32g x y z
            142  7
             8a 0 q 3
             8b 0 q 8
            16c 0 0 0
            16d 0 q z
            16e x 0 q
            16f x v 8
            32g x y z
            143  4
             1a 0 0 z
             1b 1 2 z
             1c 2 1 z
             3d x y z
            144  1
             3a x y z
            145  1
             3a x y z
            146  2
             3a 0 0 z
             9b x y z
            147  7
             1a 0 0 0
             1b 0 0 h
             2c 0 0 z
             2d 1 2 z
             3e h 0 0
             3f h 0 h
             6g x y z
            148  6
             3a 0 0 0
             3b 0 0 h
             6c 0 0 z
             9d h 0 h
             9e h 0 0
            18f x y z
            149 12
             1a 0 0 0
             1b 0 0 h
             1c 1 2 0
             1d 1 2 h
             1e 2 1 0
             1f 2 1 h
             2g 0 0 z
             2h 1 2 z
             2i 2 1 z
             3j x - 0
             3k x - h
             6l x y z
            150  7
             1a 0 0 0
             1b 0 0 h
             2c 0 0 z
             2d 1 2 z
             3e x 0 0
             3f x 0 h
             6g x y z
            151  3
             3a x - 1
             3b x - 5
             6c x y z
            152  3
             3a x 0 1
             3b x 0 5
             6c x y z
            153  3
             3a x - 2
             3b x - 6
             6c x y z
            154  3
             3a x 0 2
             3b x 0 6
             6c x y z
            155  6
             3a 0 0 0
             3b 0 0 h
             6c 0 0 z
             9d x 0 0
             9e x 0 h
            18f x y z
            156  5
             1a 0 0 z
             1b 1 2 z
             1c 2 1 z
             3d x - z
             6e x y z
            157  4
             1a 0 0 z
             2b 1 2 z
             3c x 0 z
             6d x y z
            158  4
             2a 0 0 z
             2b 1 2 z
             2c 2 1 z
             6d x y z
            159  3
             2a 0 0 z
             2b 1 2 z
             6c x y z
            160  3
             3a 0 0 z
             9b x - z
            18c x y z
            161  2
             6a 0 0 z
            18b x y z
            162 12
             1a 0 0 0
             1b 0 0 h
             2c 1 2 0
             2d 1 2 h
             2e 0 0 z
             3f h 0 0
             3g h 0 h
             4h 1 2 z
             6i x - 0
             6j x - h
             6k x 0 z
            12l x y z
            163  9
             2a 0 0 q
             2b 0 0 0
             2c 1 2 q
             2d 2 1 q
             4e 0 0 z
             4f 1 2 z
             6g h 0 0
             6h x - q
            12i x y z
            164 10
             1a 0 0 0
             1b 0 0 h
             2c 0 0 z
             2d 1 2 z
             3e h 0 0
             3f h 0 h
             6g x 0 0
             6h x 0 h
             6i x - z
            12j x y z
            165  7
             2a 0 0 q
             2b 0 0 0
             4c 0 0 z
             4d 1 2 z
             6e h 0 0
             6f x 0 q
            12g x y z
            166  9
             3a 0 0 0
             3b 0 0 h
             6c 0 0 z
             9d h 0 h
             9e h 0 0
            18f x 0 0
            18g x 0 h
            18h x - z
            36i x y z
            167  6
             6a 0 0 q
             6b 0 0 0
            12c 0 0 z
            18d h 0 0
            18e x 0 q
            36f x y z
            168  4
             1a 0 0 z
             2b 1 2 z
             3c h 0 z
             6d x y z
            169  1
             6a x y z
            170  1
             6a x y z
            171  3
             3a 0 0 z
             3b h h z
             6c x y z
            172  3
             3a 0 0 z
             3b h h z
             6c x y z
            173  3
             2a 0 0 z
             2b 1 2 z
             6c x y z
            174 12
             1a 0 0 0
             1b 0 0 h
             1c 1 2 0
             1d 1 2 h
             1e 2 1 0
             1f 2 1 h
             2g 0 0 z
             2h 1 2 z
             21 2 1 z
             3j x y 0
             3k x y h
             6l x y z
            175 12
             1a 0 0 0
             1b 0 0 h
             2c 1 2 0
             2d 1 2 h
             2e 0 0 z
             3f h 0 0
             3g h 0 h
             4h 1 2 z
             6i h 0 z
             6j x y 0
             6k x y h
            12l x y z
            176  9
             2a 0 0 q
             2b 0 0 0
             2c 1 2 q
             2d 2 1 q
             4e 0 0 z
             4f 1 2 z
             6g h 0 0
             6h x y q
            12i x y z
            177 14
             1a 0 0 0
             1b 0 0 h
             2c 1 2 0
             2d 1 2 h
             2e 0 0 z
             3f h 0 0
             3g h 0 h
             4h 1 2 z
             6i h 0 z
             6j x 0 0
             6k x 0 h
             6l x - 0
             6m x - h
            12n x y z
            178  3
             6a x 0 0
             6b x d q
            12c x y z
            179  3
             6a x 0 0
             6b x d q
            12c x y z
            180 11
             3a 0 0 0
             3b 0 0 h
             3c h 0 0
             3d h 0 h
             6e 0 0 z
             6f h 0 z
             6g x 0 0
             6h x 0 h
             6i x d 0
             6j x d h
            12k x y z
            181 11
             3a 0 0 0
             3b 0 0 h
             3c h 0 0
             3d h 0 h
             6e 0 0 z
             6f h 0 z
             6g x 0 0
             6h x 0 h
             6i x d 0
             6j x d h
            12k x y z
            182  9
             2a 0 0 0
             2b 0 0 q
             2c 1 2 q
             2d 2 1 q
             4e 0 0 z
             4f 1 2 z
             6g x 0 0
             6h x d q
            12i x y z
            183  6
             1a 0 0 z
             2b 1 2 z
             3c h 0 z
             6d x 0 z
             6e x - z
            12f x y z
            184  4
             2a 0 0 z
             4b 1 2 z
             6c h 0 z
            12d x y z
            185  4
             2a 0 0 z
             4b 1 2 z
             6c x 0 z
            12d x y z
            186  4
             2a 0 0 z
             2b 1 2 z
             6c x - z
            12d x y z
            187 15
             1a 0 0 0
             1b 0 0 h
             1c 1 2 0
             1d 1 2 h
             1e 2 1 0
             1f 2 1 h
             2g 0 0 z
             2h 1 2 z
             2i 2 1 z
             3j x - 0
             3k x - h
             6l x y 0
             6m x y h
             6n x - z
            12o x y z
            188 12
             2a 0 0 0
             2b 0 0 q
             2c 1 2 0
             2d 1 2 q
             2e 2 1 0
             2f 2 1 q
             4g 0 0 z
             4h 1 2 z
             4i 2 1 z
             6j x - 0
             6k x y q
            12l x y z
            189 12
             1a 0 0 0
             1b 0 0 h
             2c 1 2 0
             2d 1 2 h
             2e 0 0 z
             3f x 0 0
             3g x 0 h
             4h 1 2 z
             6i x 0 z
             6j x y 0
             6k x y h
            12l x y z
            190  9
             2a 0 0 0
             2b 0 0 q
             2c 1 2 q
             2d 2 1 q
             4e 0 0 z
             4f 1 2 z
             6g x 0 0
             6h x y q
            12i x y z
            191 18
             1a 0 0 0
             1b 0 0 h
             2c 1 2 0
             2d 1 2 h
             2e 0 0 z
             3f h 0 0
             3g h 0 h
             4h 1 2 z
             6i h 0 z
             6j x 0 0
             6k x 0 h
             6l x d 0
             6m x d h
            12n x 0 z
            12o x d z
            12p x y 0
            12q x y h
            24r x y z
            192 13
             2a 0 0 q
             2b 0 0 0
             4c 1 2 q
             4d 1 2 0
             4e 0 0 z
             6f h 0 q
             6g h 0 0
             8h 1 2 z
            12i h 0 z
            12j x 0 q
            12k x d q
            12l x y 0
            24m x y z
            193 12
             2a 0 0 q
             2b 0 0 0
             4c 1 2 q
             4d 1 2 0
             4e 0 0 z
             6f h 0 0
             6g x 0 q
             8h 1 2 z
            12i x d 0
            12j x y q
            12k x 0 z
            24l x y z
            194 12
             2a 0 0 0
             2b 0 0 q
             2c 1 2 q
             2d 2 1 q
             4e 0 0 z
             4f 1 2 z
             6g h 0 0
             6h x d q
            12i x 0 0
            12j x y q
            12k x d z
            24l x y z
            195 10
             1a 0 0 0
             1b h h h
             3c 0 h h
             3d h 0 0
             4e x x x
             6f x 0 0
             6g x 0 h
             6h x h 0
             6i x h h
            12j x y z
            196  8
             4a 0 0 0
             4b h h h
             4c q q q
             4d t t t
            16e x x x
            24f x 0 0
            24g x q q
            48h x y z
            197  6
             2a 0 0 0
             6b 0 h h
             8c x x x
            12d x 0 0
            12e x h 0
            24f x y z
            198  2
             4a x x x
            12b x y z
            199  3
             8a x x x
            12b x 0 q
            24c x y z
            200 12
             1a 0 0 0
             1b h h h
             3c 0 h h
             3d h 0 0
             6e x 0 0
             6f x 0 h
             6g x h 0
             6h x h h
             8i x x x
            12j 0 y z
            12k h y z
            24l x y z
            201  8
             2a 0 0 0
             4b q q q
             4c t t t
             6d 0 h h
             8e x x x
            12f x 0 0
            12g x h 0
            24h x y z
            201  8
             2a q q q
             4b 0 0 0
             4c h h h
             6d q t t
             8e x x x
            12f x q q
            12g x t q
            24h x y z
            202  9
             4a 0 0 0
             4b h h h
             8c q q q
            24d 0 q q
            24e x 0 0
            32f x x x
            48g x q q
            48h 0 y z
            96i x y z
            203  7
             8a 0 0 0
             8b h h h
            16c 8 8 8
            16d f f f
            32e x x x
            48f x 0 0
            96g x y z
            203  7
             8a 8 8 8
             8b f f f
            16c 0 0 0
            16d h h h
            32e x x x
            48f x 8 8
            96g x y z
            204  8
             2a 0 0 0
             6b 0 h h
             8c q q q
            12d x 0 0
            12e x 0 h
            16f x x x
            24g 0 y z
            48h x y z
            205  4
             4a 0 0 0
             4b h h h
             8c x x x
            24d x y z
            206  5
             8a 0 0 0
             8b q q q
            16c x x x
            24d x 0 q
            48e x y z
            207 11
             1a 0 0 0
             1b h h h
             3c 0 h h
             3d h 0 0
             6e x 0 0
             6f x h h
             8g x x x
            12h x h 0
            12i 0 y y
            12j h y y
            24k x y z
            208 13
             2a 0 0 0
             4b q q q
             4c t t t
             6d 0 h h
             6e q 0 h
             6f q h 0
             8g x x x
            12h x 0 0
            12i x 0 h
            12j x h 0
            12k q y m
            12l q y p
            24m x y z
            209 10
             4a 0 0 0
             4b h h h
             8c q q q
            24d 0 q q
            24e x 0 0
            32f x x x
            48g 0 y y
            48h h y y
            48i x q q
            96j x y z
            210  8
             8a 0 0 0
             8b h h h
            16c 8 8 8
            16d f f f
            32e x x x
            48f x 0 0
            48g 8 y n
            96h x y z
            211 10
             2a 0 0 0
             6b 0 h h
             8c q q q
            12d q h 0
            12e x 0 0
            16f x x x
            24g x h 0
            24h 0 y y
            24i q y m
            48j x y z
            212  5
             4a 8 8 8
             4b f f f
             8c x x x
            12d 8 y n
            24e x y z
            213  5
             4a 3 3 3
             4b 7 7 7
             8c x x x
            12d 8 y r
            24e x y z
            214  9
             8a 8 8 8
             8b 7 7 7
            12c 8 0 q
            12d f 0 q
            16e x x x
            24f x 0 q
            24g 8 y r
            24h 8 y n
            48i x y z
            215 10
             1a 0 0 0
             1b h h h
             3c 0 h h
             3d h 0 0
             4e x x x
             6f x 0 0
             6g x h h
            12h x h 0
            12i x x z
            24j x y z
            216  9
             4a 0 0 0
             4b h h h
             4c q q q
             4d t t t
            16e x x x
            24f x 0 0
            24g x q q
            48h x x z
            96i x y z
            217  8
             2a 0 0 0
             6b 0 h h
             8c x x x
            12d q h 0
            12e x 0 0
            24f x h 0
            24g x x z
            48h x y z
            218  9
             2a 0 0 0
             6b 0 h h
             6c q h 0
             6d q 0 h
             8e x x x
            12f x 0 0
            12g x h 0
            12h x 0 h
            24i x y z
            219  8
             8a 0 0 0
             8b q q q
            24c 0 q q
            24d q 0 0
            32e x x x
            48f x 0 0
            48g x q q
            96h x y z
            220  5
            12a 3 0 q
            12b 7 0 q
            16c x x x
            24d x 0 q
            48e x y z
            221 14
             1a 0 0 0
             1b h h h
             3c 0 h h
             3d h 0 0
             6e x 0 0
             6f x h h
             8g x x x
            12h x h 0
            12i 0 y y
            12j h y y
            24k 0 y z
            24l h y z
            24m x x z
            48n x y z
            222  9
             2a 0 0 0
             6b 0 h h
             8c q q q
            12d q 0 h
            12e x 0 0
            16f x x x
            24g x 0 h
            24h 0 y y
            48i x y z
            222  9
             2a q q q
             6b t q q
             8c 0 0 0
            12d 0 t q
            12e x q q
            16f x x x
            24g x t q
            24h q y y
            48i x y z
            223 12
             2a 0 0 0
             6b 0 h h
             6c q 0 h
             6d q h 0
             8e q q q
            12f x 0 0
            12g x 0 h
            12h x h 0
            16i x x x
            24j q y p
            24k 0 y z
            48l x y z
            224 12
             2a 0 0 0
             4b q q q
             4c t t t
             6d 0 h h
             8e x x x
            12f q 0 h
            12g x 0 0
            24h x 0 h
            24i q y m
            24j q y p
            24k x x z
            48l x y z
            224 12
             2a q q q
             4b 0 0 0
             4c h h h
             6d q t t
             8e x x x
            12f h q t
            12g x q q
            24h x q t
            24i 0 y p
            24j h y p
            24k x x z
            48l x y z
            225 12
             4a 0 0 0
             4b h h h
             8c q q q
            24d 0 q q
            24e x 0 0
            32f x x x
            48g x q q
            48h 0 y y
            48i h y y
            96j 0 y z
            96k x x z
            92l x y z
            226 10
             8a q q q
             8b 0 0 0
            24c q 0 0
            24d 0 q q
            48e x 0 0
            48f x q q
            64g x x x
            96h q y y
            96i 0 y z
            92j x y z
            227  9
             8a 0 0 0
             8b h h h
            16c 8 8 8
            16d f f f
            32e x x x
            48f x 0 0
            96g x x z
            96h 8 y n
            92i x y z
            227  9
             8a 8 8 8
             8b 3 3 3
            16c 0 0 0
            16d h h h
            32e x x x
            48f x 8 8
            96g x x z
            96h 0 y w
            92i x y z
            228  8
            16a 0 0 0
            32b 8 8 8
            32c 3 3 3
            48d q 0 0
            64e x x x
            96f x 0 0
            96g 8 y n
            92h x y z
            228  8
            16a 8 8 8
            32b q q q
            32c 0 0 0
            48d 7 8 8
            64e x x x
            96f x 8 8
            96g q y w
            92h x y z
            229 12
             2a 0 0 0
             6b 0 h h
             8c q q q
            12d q 0 h
            12e x 0 0
            16f x x x
            24g x 0 h
            24h 0 y y
            48i q y m
            48j 0 y z
            48k x x z
            96l x y z
            230  8
            16a 0 0 0
            16b 8 8 8
            24c 8 0 q
            24d 3 0 q
            32e x x x
            48f x 0 q
            48g 8 y n
            96h x y z
        '''
        return wyckoff

    def generator_database(self):
        generator = '''
              1  1 1 C11   P1
             1 0 1 0 1 0 1
              2  1 1 Ci1   P-1
            25 0 1 0 1 0 1
              3  1 1 C21   P2
             3 0 1 0 1 0 1
              3  1 1 C21   P2
             4 0 1 0 1 0 1
              4  1 1 C22   P2_1
             3 0 1 1 2 0 1
              4  1 1 C22   P2_1
             4 0 1 0 1 1 2
              5  4 1 C23   C2
             3 0 1 0 1 0 1
              5  3 1 C23   C2
             3 0 1 0 1 0 1
              5  3 1 C23   C2
             4 0 1 0 1 0 1
              6  1 1 Cs1   Pm
            27 0 1 0 1 0 1
              6  1 1 Cs1   Pm
            28 0 1 0 1 0 1
              7  1 1 Cs2   Pc
            27 0 1 0 1 1 2
              7  1 1 Cs2   Pc
            27 1 2 0 1 1 2
              7  1 1 Cs2   Pc
            27 1 2 0 1 0 1
              7  1 1 Cs2   Pc
            28 1 2 0 1 0 1
              7  1 1 Cs2   Pc
            28 1 2 1 2 0 1
              7  1 1 Cs2   Pc
            28 0 1 1 2 0 1
              8  4 1 Cs3   Cm
            27 0 1 0 1 0 1
              8  3 1 Cs3   Cm
            27 0 1 0 1 0 1
              8  3 1 Cs3   Cm
            28 0 1 0 1 0 1
              9  4 1 Cs4   Cc
            27 0 1 0 1 1 2
              9  3 1 Cs4   Cc
            27 1 2 0 1 0 1
              9  3 1 Cs4   Cc
            28 0 1 1 2 0 1
             10  1 2 C2h1  P2/m
             3 0 1 0 1 0 1
            25 0 1 0 1 0 1
             10  1 2 C2h1  P2/m
             4 0 1 0 1 0 1
            25 0 1 0 1 0 1
             11  1 2 C2h2  P2_1/m
             3 0 1 1 2 0 1
            25 0 1 0 1 0 1
             11  1 2 C2h2  P2_1/m
             4 0 1 0 1 1 2
            25 0 1 0 1 0 1
             12  4 2 C2h3  C2/m
             3 0 1 0 1 0 1
            25 0 1 0 1 0 1
             12  3 2 C2h3  C2/m
             3 0 1 0 1 0 1
            25 0 1 0 1 0 1
             12  3 2 C2h3  C2/m
             4 0 1 0 1 0 1
            25 0 1 0 1 0 1
             13  1 2 C2h4  P2/c
             3 0 1 0 1 1 2
            25 0 1 0 1 0 1
             13  1 2 C2h4  P2/c
             3 1 2 0 1 1 2
            25 0 1 0 1 0 1
             13  1 2 C2h4  P2/c
             3 1 2 0 1 0 1
            25 0 1 0 1 0 1
             13  1 2 C2h4  P2/c
             4 1 2 0 1 0 1
            25 0 1 0 1 0 1
             13  1 2 C2h4  P2/c
             4 1 2 1 2 0 1
            25 0 1 0 1 0 1
             13  1 2 C2h4  P2/c
             4 0 1 1 2 0 1
            25 0 1 0 1 0 1
             14  1 2 C2h5  P2_1/c
             3 0 1 1 2 1 2
            25 0 1 0 1 0 1
             14  1 2 C2h5  P2_1/c
             3 1 2 1 2 1 2
            25 0 1 0 1 0 1
             14  1 2 C2h5  P2_1/c
             3 1 2 1 2 0 1
            25 0 1 0 1 0 1
             14  1 2 C2h5  P2_1/c
             4 1 2 0 1 1 2
            25 0 1 0 1 0 1
             14  1 2 C2h5  P2_1/c
             4 1 2 1 2 1 2
            25 0 1 0 1 0 1
             14  1 2 C2h5  P2_1/c
             4 0 1 1 2 1 2
            25 0 1 0 1 0 1
             15  4 2 C2h6  C2/c
             3 0 1 0 1 1 2
            25 0 1 0 1 0 1
             15  3 2 C2h6  C2/c
             3 1 2 0 1 0 1
            25 0 1 0 1 0 1
             15  3 2 C2h6  C2/c
             4 0 1 1 2 0 1
            25 0 1 0 1 0 1
             16  1 2 D21   P222
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
             17  1 2 D22   P22_1
             2 0 1 0 1 0 1
             4 0 1 0 1 1 2
             18  1 2 D23   P2_12_12
             2 1 2 1 2 0 1
             3 1 2 1 2 0 1
             19  1 2 D24   P2_12_12_1
             2 1 2 1 2 0 1
             3 0 1 1 2 1 2
             20  4 2 D25   C222_1
             2 0 1 0 1 0 1
             3 0 1 0 1 1 2
             21  4 2 D26   C222
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
             22  2 2 D27   F222
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
             23  3 2 D28   I222
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
             24  3 2 D29   I2_12_12_1
             2 1 2 1 2 0 1
             3 0 1 1 2 1 2
             25  1 2 C2v1  Pmm2
             4 0 1 0 1 0 1
            26 0 1 0 1 0 1
             25  1 2 C2v1  Pmm2
             4 0 1 0 1 0 1
            37 0 1 0 1 0 1
             26  1 2 C2v2  Pmc2_1
             4 0 1 0 1 1 2
            26 0 1 0 1 0 1
             27  1 2 C2v3  Pcc2
             4 0 1 0 1 0 1
            26 0 1 0 1 1 2
             28  1 2 C2v4  Pma2
             4 0 1 0 1 0 1
            26 1 2 0 1 0 1
             29  1 2 C2v5  Pca2_1
             4 0 1 0 1 1 2
            26 1 2 0 1 1 2
             30  1 2 C2v6  Pnc2
             4 0 1 0 1 0 1
            26 0 1 1 2 1 2
             31  1 2 C2v7  Pmn2_1
             4 1 2 0 1 1 2
            26 0 1 0 1 0 1
             32  1 2 C2v8  Pba2
             4 0 1 0 1 0 1
            26 1 2 1 2 0 1
             33  1 2 C2v9  Pna2_1
             4 0 1 0 1 1 2
            26 1 2 1 2 1 2
             34  1 2 C2v10 Pnn2
             4 0 1 0 1 0 1
            26 1 2 1 2 1 2
             35  4 2 C2v11 Cmm2
             4 0 1 0 1 0 1
            26 0 1 0 1 0 1
             36  4 2 C2v12 Cmc2_1
             4 0 1 0 1 1 2
            26 0 1 0 1 0 1
             37  4 2 C2v13 Ccc2
             4 0 1 0 1 0 1
            26 0 1 0 1 1 2
             38  4 2 C2v14 Amm2
             3 0 1 0 1 0 1
            26 0 1 0 1 0 1
             39  4 2 C2v15 Abm2
             3 0 1 0 1 0 1
            26 1 2 0 1 0 1
             40  4 2 C2v16 Ama2
             3 0 1 0 1 0 1
            26 0 1 0 1 1 2
             41  4 2 C2v17 Aba2
             3 0 1 0 1 0 1
            26 1 2 0 1 1 2
             42  2 2 C2v18 Fmm2
             4 0 1 0 1 0 1
            26 0 1 0 1 0 1
             43  2 2 C2v19 Fdd2
             4 0 1 0 1 0 1
            26 1 4 1 4 1 4
             44  3 2 C2v20 Imm2
             4 0 1 0 1 0 1
            26 0 1 0 1 0 1
             45  3 2 C2v21 Iba2
             4 0 1 0 1 0 1
            26 1 2 1 2 0 1
             46  3 2 C2v22 Ima2
             4 0 1 0 1 0 1
            26 1 2 0 1 0 1
             47  1 3 D2h1  Pmmm
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
            25 0 1 0 1 0 1
             48  1 3 D2h2  Pnnn
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
            25 1 2 1 2 1 2
             48  1 3 D2h2  Pnnn
             2 0 1 1 2 1 2
             3 1 2 0 1 1 2
            25 0 1 0 1 0 1
             49  1 3 D2h3  Pccm
             2 0 1 0 1 1 2
             3 0 1 0 1 1 2
            25 0 1 0 1 0 1
             50  1 3 D2h4  Pban
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
            25 1 2 1 2 0 1
             50  1 3 D2h4  Pban
             2 0 1 1 2 0 1
             3 1 2 0 1 0 1
            25 0 1 0 1 0 1
             51  1 3 D2h5  Pmma
             2 1 2 0 1 0 1
             3 0 1 0 1 0 1
            25 0 1 0 1 0 1
             52  1 3 D2h6  Pnna
             2 0 1 1 2 1 2
             3 1 2 1 2 1 2
            25 0 1 0 1 0 1
             53  1 3 D2h7  Pmna
             2 0 1 0 1 0 1
             3 1 2 0 1 1 2
            25 0 1 0 1 0 1
             54  1 3 D2h8  Pcca
             2 1 2 0 1 1 2
             3 0 1 0 1 1 2
            25 0 1 0 1 0 1
             55  1 3 D2h9  Pbam
             2 1 2 1 2 0 1
             3 1 2 1 2 0 1
            26 1 2 1 2 0 1
             56  1 3 D2h10 Pccn
             2 1 2 0 1 1 2
             3 0 1 1 2 1 2
            25 0 1 0 1 0 1
             57  1 3 D2h11 Pbcm
             2 0 1 1 2 0 1
             3 0 1 1 2 1 2
            25 0 1 0 1 0 1
             58  1 3 D2h12 Pnnm
             2 1 2 1 2 1 2
             3 1 2 1 2 1 2
            25 0 1 0 1 0 1
             59  1 3 D2h13 Pmmn
             2 1 2 1 2 0 1
             3 1 2 1 2 0 1
            25 1 2 1 2 0 1
             59  1 3 D2h13 Pmmn
             2 1 2 0 1 0 1
             3 0 1 1 2 0 1
            25 0 1 0 1 0 1
             60  1 3 D2h14 Pbcn
             2 1 2 1 2 0 1
             3 0 1 0 1 1 2
            25 0 1 0 1 0 1
             61  1 3 D2h15 Pbca
             2 1 2 1 2 0 1
             3 0 1 1 2 1 2
            25 0 1 0 1 0 1
             62  1 3 D2h16 Pnma
             2 1 2 1 2 1 2
             3 0 1 1 2 0 1
            25 0 1 0 1 0 1
             63  4 3 D2h17 Cmcm
             2 0 1 0 1 0 1
             3 0 1 0 1 1 2
            25 0 1 0 1 0 1
             64  4 3 D2h18 Cmca
             2 0 1 0 1 0 1
             3 0 1 1 2 1 2
            25 0 1 0 1 0 1
             65  4 3 D2h19 Cmmm
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
            25 0 1 0 1 0 1
             66  4 3 D2h20 Cccm
             2 0 1 0 1 1 2
             3 0 1 0 1 1 2
            25 0 1 0 1 0 1
             67  4 3 D2h21 Cmma
             2 0 1 0 1 0 1
             3 0 1 1 2 0 1
            25 0 1 0 1 0 1
             68  4 3 D2h22 Ccca
             2 1 2 1 2 0 1
             3 0 1 0 1 0 1
            25 0 1 1 2 1 2
             68  4 3 D2h22 Ccca
             2 1 2 0 1 1 2
             3 0 1 0 1 1 2
            25 0 1 0 1 0 1
             69  2 3 D2h23 Fmmm
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
            25 0 1 0 1 0 1
             70  2 3 D2h24 Fddd
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
            25 1 4 1 4 1 4
             70  2 3 D2h24 Fddd
             2 0 1 3 4 3 4
             3 3 4 0 1 3 4
            25 0 1 0 1 0 1
             71  3 3 D2h25 Immm
             2 0 1 0 1 0 1
             3 0 1 0 1 0 1
            25 0 1 0 1 0 1
             72  3 3 D2h26 Ibam
             2 1 2 1 2 0 1
             3 1 2 1 2 0 1
            25 0 1 0 1 0 1
             73  3 3 D2h27 Ibca
             2 1 2 1 2 0 1
             3 0 1 1 2 1 2
            25 0 1 0 1 0 1
             74  3 3 D2h28 Imma
             2 0 1 0 1 0 1
             3 0 1 1 2 0 1
            25 0 1 0 1 0 1
             75  1 1 C41   P4
            21 0 1 0 1 0 1
             76  1 1 C42   P4_1
            21 0 1 0 1 1 4
             77  1 1 C43   P4_2
            21 0 1 0 1 1 2
             78  1 1 C44   P4_3
            21 0 1 0 1 3 4
             79  3 1 C45   I4
            21 0 1 0 1 0 1
             80  3 1 C46   I4_1
            21 0 1 1 2 1 4
             81  1 1 S41   P-4
            45 0 1 0 1 0 1
             82  3 1 S42   I-4
            45 0 1 0 1 0 1
             83  1 2 C4h1  P4/m
            21 0 1 0 1 0 1
            25 0 1 0 1 0 1
             84  1 2 C4h2  P4_2/m
            21 0 1 0 1 1 2
            25 0 1 0 1 0 1
             85  1 2 C4h3  P4/n
            21 1 2 1 2 0 1
            25 1 2 1 2 0 1
             85  1 2 C4h3  P4/n
            21 1 2 0 1 0 1
            25 0 1 0 1 0 1
             86  1 2 C4h4  P4_2/n
            21 1 2 1 2 1 2
            25 1 2 1 2 1 2
             86  1 2 C4h4  P4_2/n
            21 0 1 1 2 1 2
            25 0 1 0 1 0 1
             87  3 2 C4h5  I4/m
            21 0 1 0 1 0 1
            25 0 1 0 1 0 1
             88  3 2 C4h6  I4_1/a
            21 0 1 1 2 1 4
            25 0 1 1 2 1 4
             88  3 2 C4h6  I4_1/a
            21 3 4 1 4 1 4
            25 0 1 0 1 0 1
             89  1 3 D41   P422
             2 0 1 0 1 0 1
            13 0 1 0 1 0 1
            21 0 1 0 1 0 1
             90  1 3 D42   P42_12
             2 1 2 1 2 0 1
            13 0 1 0 1 0 1
            21 1 2 1 2 0 1
             91  1 3 D43   P4_122
             2 0 1 0 1 1 2
            13 0 1 0 1 3 4
            21 0 1 0 1 1 4
             92  1 3 D44   P4_12_12
             2 1 2 1 2 3 4
            13 0 1 0 1 0 1
            21 1 2 1 2 1 4
             93  1 3 D45   P4_222
             2 0 1 0 1 0 1
            13 0 1 0 1 1 2
            21 0 1 0 1 1 2
             94  1 3 D46   P4_22_12
             2 1 2 1 2 1 2
            13 0 1 0 1 0 1
            21 1 2 1 2 1 2
             95  1 3 D47   P4_322
             2 0 1 0 1 1 2
            13 0 1 0 1 1 4
            21 0 1 0 1 3 4
             96  1 3 D48   P4_32_12
             2 1 2 1 2 1 4
            13 0 1 0 1 0 1
            21 1 2 1 2 3 4
             97  3 3 D49   I422
             2 0 1 0 1 0 1
            13 0 1 0 1 0 1
            21 0 1 0 1 0 1
             98  3 3 D410  I4_122
             2 0 1 1 2 1 4
            13 1 2 1 2 1 2
            21 0 1 1 2 1 4
             99  1 2 C4v1  P4mm
            21 0 1 0 1 0 1
            26 0 1 0 1 0 1
            100  1 2 C4v2  P4bm
            21 0 1 0 1 0 1
            26 1 2 1 2 0 1
            101  1 2 C4v3  P4_2cm
            21 0 1 0 1 1 2
            26 0 1 0 1 1 2
            102  1 2 C4v4  P4_2nm
            21 1 2 1 2 1 2
            26 1 2 1 2 1 2
            103  1 2 C4v5  P4cc
            21 0 1 0 1 0 1
            26 0 1 0 1 1 2
            104  1 2 C4v6  P4nc
            21 0 1 0 1 0 1
            26 1 2 1 2 1 2
            105  1 2 C4v7  P4_2mc
            21 0 1 0 1 1 2
            26 0 1 0 1 0 1
            106  1 2 C4v8  P4_2bc
            21 0 1 0 1 1 2
            26 1 2 1 2 0 1
            107  3 2 C4v9  I4mm
            21 0 1 0 1 0 1
            26 0 1 0 1 0 1
            108  3 2 C4v10 I4cm
            21 0 1 0 1 0 1
            26 0 1 0 1 1 2
            109  3 2 C4v11 I4_1md
            21 0 1 1 2 1 4
            26 1 2 1 2 1 2
            110  3 2 C4v12 I4_1cd
            21 0 1 1 2 1 4
            26 1 2 1 2 0 1
            111  1 2 D2d1  P-42m
             2 0 1 0 1 0 1
            45 0 1 0 1 0 1
            112  1 2 D2d2  P-42c
             2 0 1 0 1 1 2
            45 0 1 0 1 0 1
            113  1 2 D2d3  P-42_1m
             2 1 2 1 2 0 1
            45 0 1 0 1 0 1
            114  1 2 D2d4  P-42_1c
             2 1 2 1 2 1 2
            45 0 1 0 1 0 1
            115  1 2 D2d5  P-4m2
            13 0 1 0 1 0 1
            45 0 1 0 1 0 1
            116  1 2 D2d6  P-4c2
            13 0 1 0 1 1 2
            45 0 1 0 1 0 1
            117  1 2 D2d7  P-4b2
            13 1 2 1 2 0 1
            45 0 1 0 1 0 1
            118  1 2 D2d8  P-4n2
            13 1 2 1 2 1 2
            45 0 1 0 1 0 1
            119  3 2 D2d9  I-4m2
            13 0 1 0 1 0 1
            45 0 1 0 1 0 1
            120  3 2 D2d10 I-4c2
            13 0 1 0 1 1 2
            45 0 1 0 1 0 1
            121  3 2 D2d11 I-42m
             2 0 1 0 1 0 1
            45 0 1 0 1 0 1
            122  3 2 D2d12 I-42d
             2 1 2 0 1 3 4
            45 0 1 0 1 0 1
            123  1 3 D4h1  P4/mmm
             2 0 1 0 1 0 1
            21 0 1 0 1 0 1
            25 0 1 0 1 0 1
            124  1 3 D4h2  P4/mcc
             2 0 1 0 1 1 2
            21 0 1 0 1 0 1
            25 0 1 0 1 0 1
            125  1 3 D4h3  P4/nbm
             2 0 1 0 1 0 1
            21 0 1 0 1 0 1
            25 1 2 1 2 0 1
            125  1 3 D4h3  P4/nbm
             2 0 1 1 2 0 1
            21 1 2 0 1 0 1
            25 0 1 0 1 0 1
            126  1 3 D4h4  P4/nnc
             2 0 1 0 1 0 1
            21 0 1 0 1 0 1
            25 1 2 1 2 1 2
            126  1 3 D4h4  P4/nnc
             2 0 1 1 2 1 2
            21 1 2 0 1 0 1
            25 0 1 0 1 0 1
            127  1 3 D4h5  P4/mbm
             2 1 2 1 2 0 1
            21 0 1 0 1 0 1
            25 0 1 0 1 0 1
            128  1 3 D4h6  P4/mnc
             2 1 2 1 2 1 2
            21 0 1 0 1 0 1
            25 0 1 0 1 0 1
            129  1 3 D4h7  P4/nmm
             2 1 2 1 2 0 1
            21 1 2 1 2 0 1
            25 1 2 1 2 0 1
            129  1 3 D4h7  P4/nmm
             2 1 2 0 1 0 1
            21 1 2 0 1 0 1
            25 0 1 0 1 0 1
            130  1 3 D4h8  P4/ncc
             2 1 2 1 2 1 2
            21 1 2 1 2 0 1
            25 1 2 1 2 0 1
            130  1 3 D4h8  P4/ncc
             2 1 2 0 1 1 2
            21 1 2 0 1 0 1
            25 0 1 0 1 0 1
            131  1 3 D4h9  P4_2/mmc
             2 0 1 0 1 0 1
            21 0 1 0 1 1 2
            25 0 1 0 1 0 1
            132  1 3 D4h10 P4_2/mcm
             2 0 1 0 1 1 2
            21 0 1 0 1 1 2
            25 0 1 0 1 0 1
            133  1 3 D4h11 P4_2/nbc
             2 0 1 0 1 1 2
            21 1 2 1 2 1 2
            25 1 2 1 2 1 2
            133  1 3 D4h11 P4_2/nbc
             2 0 1 1 2 0 1
            21 1 2 0 1 1 2
            25 0 1 0 1 0 1
            134  1 3 D4h12 P4_2/nnm
             2 0 1 0 1 0 1
            21 1 2 1 2 1 2
            25 1 2 1 2 1 2
            134  1 3 D4h12 P4_2/nnm
             2 0 1 1 2 1 2
            21 1 2 0 1 1 2
            25 0 1 0 1 0 1
            135  1 3 D4h13 P4_2/mbc
             2 1 2 1 2 0 1
            21 0 1 0 1 1 2
            25 0 1 0 1 0 1
            136  1 3 D4h14 P4_2/mnm
             2 1 2 1 2 1 2
            21 1 2 1 2 1 2
            25 0 1 0 1 0 1
            137  1 3 D4h15 P4_2/nmc
             2 1 2 1 2 1 2
            21 1 2 1 2 1 2
            25 1 2 1 2 1 2
            137  1 3 D4h15 P4_2/nmc
             2 1 2 0 1 0 1
            21 1 2 0 1 1 2
            25 0 1 0 1 0 1
            138  1 3 D4h16 P4_2/ncm
             2 1 2 1 2 0 1
            21 1 2 1 2 1 2
            25 1 2 1 2 1 2
            138  1 3 D4h16 P4_2/ncm
             2 1 2 0 1 1 2
            21 1 2 0 1 1 2
            25 0 1 0 1 0 1
            139  3 3 D4h17 I4/mmm
             2 0 1 0 1 0 1
            21 0 1 0 1 0 1
            25 0 1 0 1 0 1
            140  3 3 D4h18 I4/mcm
             2 0 1 0 1 1 2
            21 0 1 0 1 0 1
            25 0 1 0 1 0 1
            141  3 3 D4h19 I4_1/amd
             2 0 1 1 2 1 4
            21 0 1 1 2 1 4
            25 0 1 1 2 1 4
            141  3 3 D4h19 I4_1/amd
             2 0 1 0 1 0 1
            21 1 4 3 4 1 4
            25 0 1 0 1 0 1
            142  3 3 D4h20 I4_1/acd
             2 0 1 1 2 3 4
            21 0 1 1 2 1 4
            25 0 1 1 2 1 4
            142  3 3 D4h20 I4_1/acd
             2 0 1 0 1 1 2
            21 1 4 3 4 1 4
            25 0 1 0 1 0 1
            143  0 1 C31   P3
             3 0 1 0 1 0 1
            144  0 1 C32   P3_1
             3 0 1 0 1 1 3
            145  0 1 C33   P3_2
             3 0 1 0 1 2 3
            146 -1 1 C34   R3
             3 0 1 0 1 0 1
            147  0 2 C3i1  P-3
             3 0 1 0 1 0 1
            13 0 1 0 1 0 1
            148 -1 2 C3i2  R-3
             3 0 1 0 1 0 1
            13 0 1 0 1 0 1
            149  0 2 D31   P312
             3 0 1 0 1 0 1
             7 0 1 0 1 0 1
            150  0 2 D32   P321
             3 0 1 0 1 0 1
            10 0 1 0 1 0 1
            151  0 2 D33   P3_112
             3 0 1 0 1 1 3
             7 0 1 0 1 1 3
            152  0 2 D34   P3_121
             3 0 1 0 1 1 3
            10 0 1 0 1 2 3
            153  0 2 D35   P3_212
             3 0 1 0 1 2 3
             7 0 1 0 1 2 3
            154  0 2 D36   P3_221
             3 0 1 0 1 2 3
            10 0 1 0 1 1 3
            155 -1 2 D37   R32
             3 0 1 0 1 0 1
            10 0 1 0 1 0 1
            156  0 2 C3v1  P3m1
             3 0 1 0 1 0 1
            22 0 1 0 1 0 1
            157  0 2 C3v2  P31m
             3 0 1 0 1 0 1
            19 0 1 0 1 0 1
            158  0 2 C3v3  P3c1
             3 0 1 0 1 0 1
            22 0 1 0 1 1 2
            159  0 2 C3v4  P31c
             3 0 1 0 1 0 1
            19 0 1 0 1 1 2
            160 -1 2 C3v5  R3m
             3 0 1 0 1 0 1
            22 0 1 0 1 0 1
            161 -1 2 C3v6  R3c
             3 0 1 0 1 0 1
            22 0 1 0 1 1 2
            162  0 3 D3d1  P-31m
             3 0 1 0 1 0 1
             7 0 1 0 1 0 1
            13 0 1 0 1 0 1
            163  0 3 D3d2  P-31c
             3 0 1 0 1 0 1
             7 0 1 0 1 1 2
            13 0 1 0 1 0 1
            164  0 3 D3d3  P-3m1
             3 0 1 0 1 0 1
            10 0 1 0 1 0 1
            13 0 1 0 1 0 1
            165  0 3 D3d4  P-3c1
             3 0 1 0 1 0 1
            10 0 1 0 1 1 2
            13 0 1 0 1 0 1
            166 -1 3 D3d5  R-3m
             3 0 1 0 1 0 1
            10 0 1 0 1 0 1
            13 0 1 0 1 0 1
            167 -1 3 D3d6  R-3c
             3 0 1 0 1 0 1
            10 0 1 0 1 1 2
            13 0 1 0 1 0 1
            168  0 1 C61   P6
             2 0 1 0 1 0 1
            169  0 1 C62   P6_1
             2 0 1 0 1 1 6
            170  0 1 C63   P6_5
             2 0 1 0 1 5 6
            171  0 1 C64   P6_2
             2 0 1 0 1 1 3
            172  0 1 C65   P6_4
             2 0 1 0 1 2 3
            173  0 1 C66   P6_3
             2 0 1 0 1 1 2
            174  0 1 C3h1  P-6
            14 0 1 0 1 0 1
            175  0 2 C6h1  P6/m
             2 0 1 0 1 0 1
            13 0 1 0 1 0 1
            176  0 2 C6h2  P6_3/m
             2 0 1 0 1 1 2
            13 0 1 0 1 0 1
            177  0 2 D61   P622
             2 0 1 0 1 0 1
             7 0 1 0 1 0 1
            178  0 2 D62   P6_122
             2 0 1 0 1 1 6
             7 0 1 0 1 1 2
            179  0 2 D63   P6_522
             2 0 1 0 1 5 6
             7 0 1 0 1 1 2
            180  0 2 D64   P6_222
             2 0 1 0 1 1 3
             7 0 1 0 1 0 1
            181  0 2 D65   P6_422
             2 0 1 0 1 2 3
             7 0 1 0 1 0 1
            182  0 2 D66   P6_322
             2 0 1 0 1 1 2
             7 0 1 0 1 1 2
            183  0 2 C6v1  P6mm
             2 0 1 0 1 0 1
            19 0 1 0 1 0 1
            184  0 2 C6v2  P6cc
             2 0 1 0 1 0 1
            19 0 1 0 1 1 2
            185  0 2 C6v3  P6_3cm
             2 0 1 0 1 1 2
            19 0 1 0 1 0 1
            186  0 2 C6v4  P6_3mc
             2 0 1 0 1 1 2
            19 0 1 0 1 1 2
            187  0 3 D3h1  P-6m2
             3 0 1 0 1 0 1
             7 0 1 0 1 0 1
            16 0 1 0 1 0 1
            188  0 3 D3h2  P-6c2
             3 0 1 0 1 0 1
             7 0 1 0 1 0 1
            16 0 1 0 1 1 2
            189  0 3 D3h3  P-62m
             3 0 1 0 1 0 1
            10 0 1 0 1 0 1
            16 0 1 0 1 0 1
            190  0 3 D3h4  P-62c
             3 0 1 0 1 0 1
            10 0 1 0 1 0 1
            16 0 1 0 1 1 2
            191  0 3 D6h1  P6/mmm
             2 0 1 0 1 0 1
             7 0 1 0 1 0 1
            13 0 1 0 1 0 1
            192  0 3 D6h2  P6/mcc
             2 0 1 0 1 0 1
             7 0 1 0 1 1 2
            13 0 1 0 1 0 1
            193  0 3 D6h3  P6_3/mcm
             2 0 1 0 1 1 2
             7 0 1 0 1 0 1
            13 0 1 0 1 0 1
            194  0 3 D6h4  P6_3/mmc
             2 0 1 0 1 1 2
             7 0 1 0 1 1 2
            13 0 1 0 1 0 1
            195  1 2 T1    P23
             2 0 1 0 1 0 1
             5 0 1 0 1 0 1
            196  2 2 T2    F23
             2 0 1 0 1 0 1
             5 0 1 0 1 0 1
            197  3 2 T3    I23
             2 0 1 0 1 0 1
             5 0 1 0 1 0 1
            198  1 2 T4    P2_13
             2 1 2 1 2 0 1
             5 0 1 0 1 0 1
            199  3 2 T5    I2_13
             2 1 2 1 2 0 1
             5 0 1 0 1 0 1
            200  1 3 Th1   Pm-3
             2 0 1 0 1 0 1
             5 0 1 0 1 0 1
            25 0 1 0 1 0 1
            201  1 3 Th2   Pn-3
             2 0 1 0 1 0 1
             5 0 1 0 1 0 1
            25 1 2 1 2 1 2
            201  1 3 Th2   Pn-3
             2 0 1 1 2 1 2
             5 0 1 0 1 0 1
            25 0 1 0 1 0 1
            202  2 3 Th3   Fm-3
             2 0 1 0 1 0 1
             5 0 1 0 1 0 1
            25 0 1 0 1 0 1
            203  2 3 Th4   Fd-3
             2 0 1 0 1 0 1
             5 0 1 0 1 0 1
            25 1 4 1 4 1 4
            203  2 3 Th4   Fd-3
             2 0 1 1 4 1 4
             5 0 1 0 1 0 1
            25 0 1 0 1 0 1
            204  3 3 Th5   Im-3
             2 0 1 0 1 0 1
             5 0 1 0 1 0 1
            25 0 1 0 1 0 1
            205  1 3 Th6   Pa-3
             2 1 2 1 2 0 1
             5 0 1 0 1 0 1
            25 0 1 0 1 0 1
            206  3 3 Th7   Ia-3
             2 1 2 1 2 0 1
             5 0 1 0 1 0 1
            25 0 1 0 1 0 1
            207  1 2 O1    P432
             5 0 1 0 1 0 1
            19 0 1 0 1 0 1
            208  1 2 O2    P4_232
             5 0 1 0 1 0 1
            19 1 2 1 2 1 2
            209  2 2 O3    F432
             5 0 1 0 1 0 1
            19 0 1 0 1 0 1
            210  2 2 O4    F4_132
             5 0 1 0 1 0 1
            19 1 4 3 4 3 4
            211  3 2 O5    I432
             5 0 1 0 1 0 1
            19 0 1 0 1 0 1
            212  1 2 O6    P4_332
             5 0 1 0 1 0 1
            19 3 4 3 4 1 4
            213  1 2 O7    P4_132
             5 0 1 0 1 0 1
            19 1 4 1 4 3 4
            214  3 2 O8    I4_132
             5 0 1 0 1 0 1
            19 1 4 1 4 3 4
            215  1 2 Td1   P-43m
             5 0 1 0 1 0 1
            43 0 1 0 1 0 1
            216  2 2 Td2   F-43m
             5 0 1 0 1 0 1
            43 0 1 0 1 0 1
            217  3 2 Td3   I-43m
             5 0 1 0 1 0 1
            43 0 1 0 1 0 1
            218  1 2 Td4   P-43n
             5 0 1 0 1 0 1
            43 1 2 1 2 1 2
            219  2 2 Td5   F-43c
             5 0 1 0 1 0 1
            43 1 2 1 2 1 2
            220  3 2 Td6   I-43d
             5 0 1 0 1 0 1
            43 3 4 3 4 1 4
            221  1 3 Oh1   Pm-3m
             5 0 1 0 1 0 1
            19 0 1 0 1 0 1
            25 0 1 0 1 0 1
            222  1 3 Oh2   Pn-3n
             5 0 1 0 1 0 1
            19 0 1 0 1 0 1
            25 1 2 1 2 1 2
            222  1 3 Oh2   Pn-3n
             5 0 1 0 1 0 1
            19 0 1 1 2 0 1
            25 0 1 0 1 0 1
            223  1 3 Oh3   Pm-3n
             5 0 1 0 1 0 1
            19 1 2 1 2 1 2
            25 0 1 0 1 0 1
            224  1 3 Oh4   Pn-3m
             5 0 1 0 1 0 1
            19 1 2 1 2 1 2
            25 1 2 1 2 1 2
            224  1 3 Oh4   Pn-3m
             5 0 1 0 1 0 1
            19 1 2 0 1 1 2
            25 0 1 0 1 0 1
            225  2 3 Oh5   Fm-3m
             5 0 1 0 1 0 1
            19 0 1 0 1 0 1
            25 0 1 0 1 0 1
            226  2 3 Oh6   Fm-3c
             5 0 1 0 1 0 1
            19 1 2 1 2 1 2
            25 0 1 0 1 0 1
            227  2 3 Oh7   Fd-3m
             5 0 1 0 1 0 1
            19 1 4 3 4 3 4
            25 1 4 1 4 1 4
            227  2 3 Oh7   Fd-3m
             5 0 1 0 1 0 1
            19 1 4 1 2 3 4
            25 0 1 0 1 0 1
            228  2 3 Oh8   Fd-3c
             5 0 1 0 1 0 1
            19 1 4 3 4 3 4
            25 3 4 3 4 3 4
            228  2 3 Oh8   Fd-3c
             5 0 1 0 1 0 1
            19 1 4 0 1 3 4
            25 0 1 0 1 0 1
            229  3 3 Oh9   Im-3m
             5 0 1 0 1 0 1
            19 0 1 0 1 0 1
            25 0 1 0 1 0 1
            230  3 3 Oh10  Ia-3d
             5 0 1 0 1 0 1
            19 1 4 1 4 3 4
            25 0 1 0 1 0 1
        '''
        return generator
