#!/usr/bin/env python3
#
# database for wyckoff position and generator
#  this data was generated by Akira Yanase
#  implemented for python library by Hiroki Funashima
#
#
# Prof. Yanase have copyright for this database.
#


class LibTspaceDataBase(object):
    def wyckoff_database(self):
        wyckoff = '''
